# Set Options
```{r purl = TRUE}
DIR = 'D:/Onedrive/__Projects/econforecasting'
PACKAGE_DIR = 'D:/Onedrive/__Projects/econforecasting/r-package' # Path to package with helper functions
DOC_DIR = 'D:/Onedrive/__Projects/econforecasting/documentation-templates' # Path to documentation .RNW file; if NULL no docs generated
INPUT_DIR = 'D:/Onedrive/__Projects/econforecasting/model-inputs' # Path to directory with inputs.r, constants.r (SQL DB info, SFTP info, etc.)
OUTPUT_DIR = 'D:/Onedrive/__Projects/econforecasting/model-outputs' # Path to location to output RDS and documentation
RESET_ALL = FALSE
VINTAGE_DATE = Sys.Date() # as.Date('2021-03-15') # Sys.Date() # Date to pull data "as-of", for general use set this as Sys.Date(); otherwise set as an older date for backtesting
```


# Initialize
```{r}
# General purpose
library(tidyverse) # General
library(data.table) # General
library(devtools) # General
library(lubridate) # Dates
# Data parse/import
library(jsonlite) # JSON Parser
library(rvest) # HTML Parser
library(httr) # CURL Interface
# SQL/Apache Spark
library(DBI) # SQL Interface
library(RPostgres) # PostgreSQL
# My package
devtools::load_all(path = PACKAGE_DIR)
devtools::document(PACKAGE_DIR)

# Set working directory
setwd(DIR)

# Read constants
source(file.path(INPUT_DIR, 'constants.r'))

# Create top-level variables
ef = list()
```

# List of structural equations
```{r}
local({
	
	# Specify structural equations
	# Where:
	#	ll refers to loglinearized equations
	#		include + and -
	#		include only basic covariate names
	#		don't include coefficient as it will be just equal to the ll steady-state
	#	estimated refers to OLS-estimated equations
	#		don't include + and -,
	#		include covariate names including lag operators (x.l1, x.l2, ...) and/or moving averages (x.m1, x.m2, ...),
	#		don't include coefficients as it will just be equal to estimated value
	#	fixed means the equation is as written
	#		include + and -,
	structEquations =
		tribble(
			~ equation, ~ type,,
			'gdp = pce + pdi + ex - im + govt', 'll',
			'pce = constant + pce.l1 + pce.l2', 'estimated',
			)
	
	# Get list of steady-state values for the log-linearized equations
	ef$ss = 

	
})
```

