# Nowcast model

# Generate Initial Forecasts

## Baseline Forecasts (Qual)
```{r}
local({

    initial = list()
    
    initial$ffr =
        m$ext$sources$cme %>%
        dplyr::filter(., varname == 'ffr') %>%
        dplyr::filter(., vdate == max(vdate)) %>%
        dplyr::filter(., date > max(ef$variables$ffr$h$base$m$date)) %>%
        dplyr::transmute(., form, date, value)
    
    initial$sofr =
        m$ext$sources$cme %>%
        dplyr::filter(., varname == 'sofr') %>%
        dplyr::filter(., vdate == max(vdate)) %>%
        dplyr::filter(., date > max(ef$variables$sofr$h$base$m$date)) %>%
        dplyr::transmute(., form, date, value)
    
    initial$inf =
        m$ext$sources$cle %>%
        dplyr::filter(., varname == 'inf') %>%
        dplyr::filter(., vdate == max(vdate)) %>%
        dplyr::filter(., date > max(ef$variables$inf$h$base$m$date)) %>%
        dplyr::transmute(., form, date, value)
    
    initial$tdns1 =
        m$ext$sources$dns %>%
        dplyr::filter(., varname == 'tdns1') %>%
        dplyr::filter(., vdate == max(vdate)) %>%
        dplyr::filter(., date > max(ef$variables$tdns1$h$base$m$date)) %>%
        dplyr::transmute(., form, date, value)
    
    initial$tdns2 =
        m$ext$sources$dns %>%
        dplyr::filter(., varname == 'tdns2') %>%
        dplyr::filter(., vdate == max(vdate)) %>%
        dplyr::filter(., date > max(ef$variables$tdns2$h$base$m$date)) %>%
        dplyr::transmute(., form, date, value)
    
    initial$tdns3 =
        m$ext$sources$dns %>%
        dplyr::filter(., varname == 'tdns3') %>%
        dplyr::filter(., vdate == max(vdate)) %>%
        dplyr::filter(., date > max(ef$variables$tdns3$h$base$m$date)) %>%
        dplyr::transmute(., form, date, value)

    initial$dpi =
        ef$variables$dpi$h$st$m %>%
        tail(., 4) %>%
        dplyr::transmute(., form = 'd1', date, value) %>%
        dplyr::bind_rows(
            .,
            tibble(
                form = 'd1',
                date = seq(from = lubridate::add_with_rollback(tail(.$date, 1), months(1)), by = '1 month', length.out = 60),
                value = 
                    c(
                        0/100,
                        -5/100,
                        -10/100,
                        rep(NA, 7),
                        rep(mean(ef$variables$dpi$h$st$m$value), 50)
                        ) %>%
                    zoo::na.spline(., method = 'natural')
            )
        ) %>%
        tail(., -4)
    
    initial$ue =
        # Take last four quarters of historical data
        ef$variables$ue$h$base$m %>%
        tail(., 4) %>%
        dplyr::transmute(., form = 'd1', date, value) %>%
        # Bind next 24 months
        dplyr::bind_rows(
            .,
            tibble(
                form = 'd1',
                date = seq(from = lubridate::add_with_rollback(tail(.$date, 1), months(1)), by = '1 month', length.out = 60)
                )
            ) %>%
        # Now join with external forecast, but use historical data if external forecast has same dates
        dplyr::left_join(
            .,
            m$ext$sources$spf %>%
                dplyr::filter(., vdate == max(vdate) & varname == 'unemp') %>%
                dplyr::transmute(., form, date, value2 = value),
            by = c('form', 'date')
        ) %>%
        dplyr::mutate(., value = ifelse(!is.na(value), value, value2)) %>%
        # Add in long run average
        dplyr::mutate(., value = ifelse(date == max(date), 5.0, value)) %>%
        # Splinal interpolate
        dplyr::mutate(., value = zoo::na.spline(value, method = 'natural')) %>%
        tail(., -4)
    
    initial$spy =
        ef$variables$ue$h$base$m %>%
        dplyr::filter(., )

    
    
    m$initialQualBaseline <<- initial 
})
```

## Other Scenario Forecsts (Qual)
```{r}
local({
    
    
})
```

## All Scenario Forecasts (Calc)
```{r}
local({
    
    
})
```


